version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    env_file: .env
    networks:
      - app-net

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:

